import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/Header/Header";
import SubmitBtn from "@/components/forms/btn/SubmitBtn";
import AdvantageCardContainer from "@/components/ui/AdvantageCardContainer/AdvantageCardContainer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Cubax HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bg_image_cloudes}>
        {/* <Image
              alt="bg_img"
              src={"/imgs/фон.png"}
              width={"800"} 
              height={"500"}
            /> */}
      </div>
      <Header />
      <main className={styles.main}>
        <section className="relative">
          <div className="txt__container">
            <h1>
              Быстровозводимые здания из стеклофибробетона сроком службы более
              100 лет
            </h1>
          </div>
          <div className="btn__container">
            <SubmitBtn onClick={() => console.log("")} txt="Оставить заявку" />
          </div>
          <div>
            <AdvantageCardContainer />
          </div>
        </section>
      </main>
    </>
  );
}
